version: '3'
services:
  asp-core-backend:
    build:
      context: ./backend/
      dockerfile: ./LuckyRest/Dockerfile
    secrets:
      - user
      - pass
    ports:
      - "5000:8080"
      - "5001:8081"
    depends_on:
      - postgres-db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  vue-frontend: 
    build: 
      context: ./frontend/
    ports:
      - 8080:80
  postgres-db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    secrets:
      - user
      - pass
    environment:
      - POSTGRES_DB=lucky_db
      - POSTGRES_USER_FILE=/run/secrets/user
      - POSTGRES_PASSWORD_FILE=/run/secrets/pass
secrets:
  user:
    file: ./user.txt
  pass:
    file: ./pass.txt