const MIN_LENGTH = 6;
const MUST_CONTAIN_UPPERCASE = true;
const MUST_CONTAIN_LOWERCASE = true;
const MUST_CONTAIN_DIGIT = true;
const MUST_CONTAIN_NON_ALPHANUMERIC = true;

export default {
  MIN_LENGTH,
  MUST_CONTAIN_UPPERCASE,
  MUST_CONTAIN_LOWERCASE,
  MUST_CONTAIN_DIGIT,
  MUST_CONTAIN_NON_ALPHANUMERIC,
}
